spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: Raqn8DZBV2ygmsPGpBsuloBy3872syiZ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-gyeuyukovgfhhk16.us.auth0.com/